name: build

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.1"
          rebar3-version: "3"
      - name: Build project
        run: gleam clean && gleam build
      - name: Generate escript
        run: gleam run -m gleescript
      - name: List current directory
        run: ls -lh
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./rango
          tag: nightly
          overwrite: true
          body: 'The release is up to date with the latest commit'